### ISSUE TITLE
XML error in the testing data?

### ISSUE THREAD

**Issue by woodrush** [manga109/manga109api#16]
https://github.com/manga109/manga109api/blob/master/tests/data_dummy/annotations/TitleB.xml#L6-L7

I found that the test XML data contains an error where the `body` tag is not a subelement of the preceding `page` tag. Is this meant to be so for testing purposes?

If so, should we put a comment about this like the following code?

```xml
<!-- This tag is not a subelement of its preceding `page` tag, for testing purposes. -->
```

Adding this line before the aforementioned tag still made the pytest pass without errors.

**Comment by kktsubota** [comment]
Thank you for your report.
It's my mistake.
So I would appreciate it if you could insert `</page>` to line 8.

**Comment by woodrush** [comment]
Thanks, created #18!
