### ISSUE TITLE
Site to download the manga109 corpus seems to be down

### ISSUE THREAD

**Issue by EricZhao9482** [manga109/manga109api#25]
Hello, 
I am interested in downloading the manga109 corpus but the site: http://www.manga109.org/en/download.html
appears to be down and I can't connect to it. 

Is there anyway for me to access the manga any other way? 
Also are there any official english translations for these manga that I can access as well?

Thanks for the help!

**Comment by matsui528** [comment]
The server is currently down but will be restored shortly.

**Comment by EricZhao9482** [comment]
ok thank you
