### ISSUE TITLE
Is there a way to get the annotations sorted in an order that a human would naturally read?

### ISSUE THREAD

**Issue by EricZhao9482** [manga109/manga109api#26]
Hello, 

Not so much an issue but a question. 
Is there anyway for me to get the annotations ordered in a way that a human would naturally read each page? 
More specifically, an order in which the manga panel frames and the text in the speech bubble would be read. 

Thank you for the help,
Eric

**Comment by woodrush** [comment]
The panels can be ordered using the panel order estimator:
https://github.com/manga109/panel-order-estimator

This tool doesn't handle the speech bubbles though. You'll have to manually do so using the results of the panel order estimation. For example, this should work:
1. Find the order the panels
2. For each speech bubble, identify which panel it belongs to
3. Order the speech bubbles locally inside each panel

**Comment by EricZhao9482** [comment]
Got it. Tysm!

**Comment by woodrush** [comment]
No problem!
