### ISSUE TITLE
Website for Manga109 Dataset Access is Down

### ISSUE THREAD

**Issue by ndrw1221** [manga109/manga109api#27]
Hello,

I would like to apply for access to the Manga109 dataset. However, the website provided for downloading the dataset appears to be currently inaccessible: https://www.manga109.org/en/download.html.

Could you please let me know if there are any alternative methods to apply for or access the dataset?

Thank you.

**Comment by ku21fan** [comment]
Thank you for reporting this issue.

We have reviewed it and confirmed that the Manga109 website cannot currently be accessed via HTTPS. While we are considering enabling HTTPS in the future, please use HTTP for now:
http://www.manga109.org/en/download.html

**Comment by ndrw1221** [comment]
Thank you for your assistance and clarification.

The HTTP link is working fine, and the issue has been resolved. I appreciate your prompt response and support.
